const {chooseChapter,showPreferences}=require('./helpers.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [390,1440]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'no-preference'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.TEST_URL||'http://127.0.0.1:4173/')+'?sec=3');await p.waitForFunction(()=>document.querySelector('#tot')?.textContent==='552');assert.equal(await p.locator('.chapter-quote').count(),8);await p.locator('#sec-3 .chapter-overview>summary').click();assert(await p.locator('#sec-3 .chapter-quote').isVisible());await p.locator('#sec-3 .chapter-quote').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/editorial-'+width+'.png'});
await showPreferences(p);await p.locator('[data-reading="brief"]').click();assert(!(await p.locator('#sec-3 .chapter-quote').isVisible()));await p.locator('[data-reading="full"]').click();
const details=p.locator('#sec-3 .src').first();await details.locator('summary').evaluate(e=>{e.click();e.click();e.click()});await p.waitForFunction(()=>{const d=document.querySelector('#sec-3 .src');return d.open&&!d.style.height});assert(await details.evaluate(e=>e.open));await details.locator('summary').click();await p.waitForFunction(()=>{const d=document.querySelector('#sec-3 .src');return !d.open&&!d.style.height});
await p.locator('#hero-chapter').click();await p.locator('.navigator-close').evaluate(e=>e.click());assert(await p.locator('#chapter-navigator').evaluate(e=>e.open&&e.classList.contains('is-closing')));await p.waitForFunction(()=>!document.getElementById('chapter-navigator').open);assert(await p.locator('#hero-chapter').evaluate(e=>e===document.activeElement));
await p.locator('#hero-chapter').click();await p.locator('[data-chapter="23"]').click();await p.waitForFunction(()=>document.getElementById('chapter-select').value==='23');assert(await p.locator('#reader-workspace').evaluate(e=>e===document.activeElement));
await p.locator('#hero-chapter').click();await p.locator('.navigator-close').evaluate(e=>e.click());await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!document.getElementById('chapter-navigator').open);assert(!(await p.locator('html').evaluate(e=>e.classList.contains('navigator-open'))));
if(width===390){await p.locator('#menu').click();assert(await p.locator('html').evaluate(e=>e.classList.contains('filters-open')));await p.locator('.sidebar-dismiss').click();assert(!(await p.locator('html').evaluate(e=>e.classList.contains('filters-open'))));assert(await p.locator('#menu').evaluate(e=>e===document.activeElement));}
assert.deepEqual(errors,[]);console.log(width+' PASS: quotes, reading modes, rapid disclosure toggles, animated dismissal, focus, reduced-motion interruption, filter closure');await p.close();}}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
